# Generated by Django 2.0.7 on 2018-09-15 02:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AplicacionOferta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('estado', models.CharField(choices=[('Activo', 'Activo'), ('Inactivo', 'Inactivo')], default='Activo', max_length=10, verbose_name='Estado')),
            ],
        ),
        migrations.CreateModel(
            name='DatosBasicosD10',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semestre', models.CharField(blank=True, max_length=2, verbose_name='Semestre')),
                ('estado_civil', models.CharField(blank=True, choices=[('Soltero', 'Soltero'), ('Casado', 'Casado'), ('Union Libre', 'Union Libre'), ('Otro', 'Otro')], default='Soltero', max_length=20, verbose_name='Estado civil')),
                ('numero_de_personas_a_cargo', models.CharField(blank=True, max_length=2, verbose_name='Numero de personas a su cargo')),
                ('posicion_familiar', models.CharField(blank=True, choices=[('Hijo(a)', 'Hijo(a)'), ('Independiente', 'Independiente'), ('Cabeza de familia', 'Cabeza de familia'), ('Esposo(a)', 'Esposo(a)')], default='Hijo(a)', max_length=50, verbose_name='Posicion familiar')),
                ('direccion_residencia', models.CharField(blank=True, max_length=50, verbose_name='Direccion actual de residencia')),
                ('estrato', models.CharField(blank=True, max_length=2, verbose_name='Estrato')),
                ('barrio', models.CharField(blank=True, max_length=50, verbose_name='Barrio')),
                ('ciudad', models.CharField(blank=True, max_length=50, verbose_name='Ciudad')),
                ('departamento', models.CharField(blank=True, max_length=50, verbose_name='Departamento')),
                ('nombre_acudiente', models.CharField(blank=True, max_length=300, verbose_name='Nombre de una persona que le de informacion')),
                ('telefono_acudiente', models.CharField(blank=True, max_length=10, verbose_name='Telefono de persona que le de informacion')),
            ],
        ),
        migrations.CreateModel(
            name='DatosEducacionD10',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo_obtenido_bachillerato', models.CharField(blank=True, max_length=50, verbose_name='Titulo obtenido')),
                ('ano_finalizacion_bachillerato', models.CharField(blank=True, max_length=4, verbose_name='Año de finalizacion bachiller')),
                ('nombre_colegio_bachillerato', models.CharField(blank=True, max_length=50, verbose_name='Nombre del establecimiento')),
                ('ciudad_colegio_bachillerato', models.CharField(blank=True, max_length=50, verbose_name='Cuidad')),
                ('semestres_otros_estudios', models.CharField(blank=True, max_length=50, verbose_name='Semestres')),
                ('plan_otros_estudios', models.CharField(blank=True, max_length=2, verbose_name='Plan de estudios o titulo obtenido')),
                ('ano_finalizacion_otros_estudios', models.CharField(blank=True, max_length=4, verbose_name='Año de finalizacion')),
                ('nombre_establecimiento_otros_estudios', models.CharField(blank=True, max_length=50, verbose_name='Nombre del establecimiento')),
                ('ciudad_establecimiento_otros_estudios', models.CharField(blank=True, max_length=30, verbose_name='Ciudad')),
            ],
        ),
        migrations.CreateModel(
            name='OfertaMonitoria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('perfil_requerido', models.CharField(max_length=800)),
                ('tipo_monitoria', models.CharField(choices=[('Docencia', 'Docencia'), ('Investigacion', 'Investigacion'), ('Administrativa', 'Administrativa'), ('Especial', 'Especial')], default='Administrativa', max_length=20, verbose_name='Tipo de Monitoria')),
                ('sede', models.CharField(choices=[('Melendez', 'Melendez'), ('San Fernando', 'San Fernando')], default='Melendez', max_length=20, verbose_name='Sede')),
                ('criterios_seleccion', models.CharField(max_length=800)),
                ('periodo_duracion', models.CharField(max_length=200)),
                ('horario_ejecucion', models.CharField(max_length=200)),
                ('horas_semanales', models.PositiveIntegerField(verbose_name='Horas de trabajo semanales')),
                ('plazo_solicitudes', models.DateField()),
                ('fecha_seleccion', models.DateField()),
                ('fecha_adjudicacion', models.DateField()),
                ('resultado', models.CharField(max_length=800)),
                ('estado', models.CharField(choices=[('Activo', 'Activo'), ('Inactivo', 'Inactivo')], default='Activo', max_length=10, verbose_name='Estado')),
            ],
        ),
        migrations.AddField(
            model_name='aplicacionoferta',
            name='oferta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='OfertaMonitorias.OfertaMonitoria'),
        ),
    ]
