# Generated by Django 2.0.7 on 2018-09-15 02:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('OfertaMonitorias', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='D10',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('Activo', 'Activo'), ('Inactivo', 'Inactivo')], default='Activo', max_length=10, verbose_name='Estado')),
                ('perfil_ocupacional', models.CharField(max_length=800)),
                ('sistemas_que_maneja', models.CharField(max_length=800)),
                ('datos_basicos', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='OfertaMonitorias.DatosBasicosD10')),
                ('datos_educacion', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='OfertaMonitorias.DatosEducacionD10')),
            ],
        ),
    ]
