# Generated by Django 2.0.7 on 2018-09-17 21:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Usuarios', '0001_initial'),
        ('OfertaMonitorias', '0002_d10'),
    ]

    operations = [
        migrations.AddField(
            model_name='aplicacionoferta',
            name='estudiante',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='Usuarios.Estudiante'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='d10',
            name='estudiante',
            field=models.OneToOneField(default='1', on_delete=django.db.models.deletion.CASCADE, to='Usuarios.Estudiante'),
            preserve_default=False,
        ),
    ]
