# Generated by Django 2.0.7 on 2018-09-18 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OfertaMonitorias', '0003_auto_20180917_1600'),
    ]

    operations = [
        migrations.CreateModel(
            name='DatosCapacitacionD10',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_establecimiento', models.CharField(blank=True, max_length=50, verbose_name='Nombre del establecimiento')),
                ('nombre_curso', models.CharField(blank=True, max_length=50, verbose_name='Nombre del curso')),
                ('duracion_cruso', models.PositiveIntegerField(verbose_name='Duracion del curso')),
                ('fecha_finalizacion_curso', models.DateTimeField()),
            ],
        ),
    ]
