# Generated by Django 2.0.7 on 2018-09-18 17:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('OfertaMonitorias', '0004_datoscapacitaciond10'),
    ]

    operations = [
        migrations.AddField(
            model_name='d10',
            name='datos_capacitacion',
            field=models.OneToOneField(default='1', on_delete=django.db.models.deletion.CASCADE, to='OfertaMonitorias.DatosCapacitacionD10'),
            preserve_default=False,
        ),
    ]
