# Generated by Django 2.0.7 on 2018-09-19 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OfertaMonitorias', '0005_d10_datos_capacitacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datoscapacitaciond10',
            name='fecha_finalizacion_curso',
            field=models.DateField(),
        ),
    ]
