# Generated by Django 2.0.7 on 2018-09-19 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OfertaMonitorias', '0006_auto_20180919_1604'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='d10',
            name='perfil_ocupacional',
        ),
        migrations.RemoveField(
            model_name='d10',
            name='sistemas_que_maneja',
        ),
        migrations.AddField(
            model_name='datosbasicosd10',
            name='perfil_ocupacional',
            field=models.CharField(default='1', max_length=800),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='datosbasicosd10',
            name='sistemas_que_maneja',
            field=models.CharField(default='sdfasdfsd', max_length=800),
            preserve_default=False,
        ),
    ]
