# Generated by Django 2.0.7 on 2018-09-21 20:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Usuarios', '0001_initial'),
        ('OfertaMonitorias', '0007_auto_20180919_1627'),
    ]

    operations = [
        migrations.AddField(
            model_name='ofertamonitoria',
            name='operario_registra',
            field=models.ForeignKey(default=6, on_delete=django.db.models.deletion.CASCADE, to='Usuarios.Operario'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='datoseducaciond10',
            name='plan_otros_estudios',
            field=models.CharField(blank=True, max_length=50, verbose_name='Plan de estudios o titulo obtenido'),
        ),
        migrations.AlterField(
            model_name='datoseducaciond10',
            name='semestres_otros_estudios',
            field=models.CharField(blank=True, max_length=2, verbose_name='Semestres'),
        ),
    ]
