# Generated by Django 2.0.7 on 2018-09-24 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OfertaMonitorias', '0008_auto_20180921_1540'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datosbasicosd10',
            name='perfil_ocupacional',
            field=models.CharField(blank=True, max_length=800),
        ),
        migrations.AlterField(
            model_name='datosbasicosd10',
            name='sistemas_que_maneja',
            field=models.CharField(blank=True, max_length=800),
        ),
        migrations.AlterField(
            model_name='datoscapacitaciond10',
            name='duracion_cruso',
            field=models.CharField(blank=True, max_length=4, verbose_name='Duracion del curso (horas)'),
        ),
    ]
