# Generated by Django 2.0.7 on 2018-09-26 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OfertaMonitorias', '0009_auto_20180924_1621'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aplicacionoferta',
            name='fecha_creacion',
        ),
        migrations.AddField(
            model_name='aplicacionoferta',
            name='fecha_modificacion',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
