# Generated by Django 2.0.7 on 2018-08-29 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProgramasAcademicos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='programaacademico',
            name='codigo_programa',
            field=models.CharField(max_length=4, unique=True, verbose_name='Codigo del programa'),
        ),
    ]
