# Generated by Django 2.0.7 on 2018-08-28 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Facultades', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facultad',
            name='estado',
            field=models.CharField(choices=[('Activo', 'Activo'), ('Inactivo', 'Inactivo')], default='Activo', max_length=10, verbose_name='Estado'),
        ),
    ]
