# Generated by Django 2.0.7 on 2018-12-19 01:49

from django.conf import settings
import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0009_alter_user_last_name_max_length'),
        ('ProgramasAcademicos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='D10',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('Activo', 'Activo'), ('Inactivo', 'Inactivo')], default='Activo', max_length=10, verbose_name='Estado')),
                ('estado_aprobacion', models.CharField(choices=[('En Revision', 'En Revision'), ('Aprobado', 'Aprobado'), ('No Aprobado', 'No Aprobado')], default='En Revision', max_length=20, verbose_name='Estado Aprobacion')),
                ('promedio_acumulado', models.CharField(blank=True, max_length=5, verbose_name='Promedio Acumulado del Estudiante')),
                ('fecha_aprobacion', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='DatosBasicosD10',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semestre', models.CharField(blank=True, max_length=2, verbose_name='Semestre')),
                ('estado_civil', models.CharField(blank=True, choices=[('Soltero', 'Soltero'), ('Casado', 'Casado'), ('Union Libre', 'Union Libre'), ('Otro', 'Otro')], default='Soltero', max_length=20, verbose_name='Estado civil')),
                ('numero_de_personas_a_cargo', models.CharField(blank=True, max_length=2, verbose_name='Numero de personas a su cargo')),
                ('posicion_familiar', models.CharField(blank=True, choices=[('Hijo(a)', 'Hijo(a)'), ('Independiente', 'Independiente'), ('Cabeza de familia', 'Cabeza de familia'), ('Esposo(a)', 'Esposo(a)')], default='Hijo(a)', max_length=50, verbose_name='Posicion familiar')),
                ('direccion_residencia', models.CharField(blank=True, max_length=50, verbose_name='Direccion actual de residencia')),
                ('estrato', models.CharField(blank=True, max_length=2, verbose_name='Estrato')),
                ('barrio', models.CharField(blank=True, max_length=50, verbose_name='Barrio')),
                ('ciudad', models.CharField(blank=True, max_length=50, verbose_name='Ciudad')),
                ('departamento', models.CharField(blank=True, max_length=50, verbose_name='Departamento')),
                ('nombre_acudiente', models.CharField(blank=True, max_length=300, verbose_name='Nombre de una persona que le de informacion')),
                ('telefono_acudiente', models.CharField(blank=True, max_length=10, verbose_name='Telefono de persona que le de informacion')),
                ('perfil_ocupacional', models.CharField(blank=True, max_length=800)),
                ('sistemas_que_maneja', models.CharField(blank=True, max_length=800)),
                ('foto', models.ImageField(upload_to='fotos/')),
            ],
        ),
        migrations.CreateModel(
            name='DatosCapacitacionD10',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_establecimiento', models.CharField(blank=True, max_length=50, verbose_name='Nombre del establecimiento')),
                ('nombre_curso', models.CharField(blank=True, max_length=50, verbose_name='Nombre del curso')),
                ('duracion_cruso', models.CharField(blank=True, max_length=4, verbose_name='Duracion del curso (horas)')),
                ('fecha_finalizacion_curso', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='DatosEducacionD10',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo_obtenido_bachillerato', models.CharField(blank=True, max_length=50, verbose_name='Titulo obtenido')),
                ('ano_finalizacion_bachillerato', models.CharField(blank=True, max_length=4, verbose_name='Año de finalizacion bachiller')),
                ('nombre_colegio_bachillerato', models.CharField(blank=True, max_length=50, verbose_name='Nombre del establecimiento')),
                ('ciudad_colegio_bachillerato', models.CharField(blank=True, max_length=50, verbose_name='Cuidad')),
                ('semestres_otros_estudios', models.CharField(blank=True, max_length=2, verbose_name='Semestres')),
                ('plan_otros_estudios', models.CharField(blank=True, max_length=50, verbose_name='Plan de estudios o titulo obtenido')),
                ('ano_finalizacion_otros_estudios', models.CharField(blank=True, max_length=4, verbose_name='Año de finalizacion')),
                ('nombre_establecimiento_otros_estudios', models.CharField(blank=True, max_length=50, verbose_name='Nombre del establecimiento')),
                ('ciudad_establecimiento_otros_estudios', models.CharField(blank=True, max_length=30, verbose_name='Ciudad')),
                ('idioma_nombre', models.CharField(blank=True, max_length=30, verbose_name='Idioma')),
                ('idioma_nivel_habla', models.CharField(blank=True, choices=[('Muy Bueno', 'Muy Bueno'), ('Bueno', 'Bueno'), ('Regular', 'Regular')], max_length=20, verbose_name='Habla')),
                ('idioma_nivel_escribe', models.CharField(blank=True, choices=[('Muy Bueno', 'Muy Bueno'), ('Bueno', 'Bueno'), ('Regular', 'Regular')], max_length=20, verbose_name='Escribe')),
                ('idioma_nivel_lee', models.CharField(blank=True, choices=[('Muy Bueno', 'Muy Bueno'), ('Bueno', 'Bueno'), ('Regular', 'Regular')], max_length=20, verbose_name='Lee')),
            ],
        ),
        migrations.CreateModel(
            name='DatosExperienciaLaboralD10',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_empresa', models.CharField(blank=True, max_length=100, verbose_name='Nombre del establecimiento')),
                ('cargo', models.CharField(blank=True, max_length=80, verbose_name='Cargo desempeñado')),
                ('funciones_realizadas', models.CharField(blank=True, max_length=800, verbose_name='Funciones realizadas')),
                ('logros', models.CharField(blank=True, max_length=800, verbose_name='Logros')),
                ('jefe_inmediato', models.CharField(blank=True, max_length=200, verbose_name='Nombre del jefe inmediato')),
                ('cargo_jefe', models.CharField(blank=True, max_length=80, verbose_name='Cargo del jefe inmediato')),
                ('telefono_empresa', models.CharField(blank=True, max_length=10, verbose_name='Telefono de la empresa')),
                ('fecha_inicio', models.DateField(blank=True, null=True)),
                ('fecha_finalizacion', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='DatosHorarioDisponibleD10',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lunes_inicio_1', models.CharField(blank=True, max_length=30, null=True)),
                ('lunes_fin_1', models.CharField(blank=True, max_length=30, null=True)),
                ('lunes_inicio_2', models.CharField(blank=True, max_length=30, null=True)),
                ('lunes_fin_2', models.CharField(blank=True, max_length=30, null=True)),
                ('lunes_inicio_3', models.CharField(blank=True, max_length=30, null=True)),
                ('lunes_fin_3', models.CharField(blank=True, max_length=30, null=True)),
                ('martes_inicio_1', models.CharField(blank=True, max_length=30, null=True)),
                ('martes_fin_1', models.CharField(blank=True, max_length=30, null=True)),
                ('martes_inicio_2', models.CharField(blank=True, max_length=30, null=True)),
                ('martes_fin_2', models.CharField(blank=True, max_length=30, null=True)),
                ('martes_inicio_3', models.CharField(blank=True, max_length=30, null=True)),
                ('martes_fin_3', models.CharField(blank=True, max_length=30, null=True)),
                ('miercoles_inicio_1', models.CharField(blank=True, max_length=30, null=True)),
                ('miercoles_fin_1', models.CharField(blank=True, max_length=30, null=True)),
                ('miercoles_inicio_2', models.CharField(blank=True, max_length=30, null=True)),
                ('miercoles_fin_2', models.CharField(blank=True, max_length=30, null=True)),
                ('miercoles_inicio_3', models.CharField(blank=True, max_length=30, null=True)),
                ('miercoles_fin_3', models.CharField(blank=True, max_length=30, null=True)),
                ('jueves_inicio_1', models.CharField(blank=True, max_length=30, null=True)),
                ('jueves_fin_1', models.CharField(blank=True, max_length=30, null=True)),
                ('jueves_inicio_2', models.CharField(blank=True, max_length=30, null=True)),
                ('jueves_fin_2', models.CharField(blank=True, max_length=30, null=True)),
                ('jueves_inicio_3', models.CharField(blank=True, max_length=30, null=True)),
                ('jueves_fin_3', models.CharField(blank=True, max_length=30, null=True)),
                ('viernes_inicio_1', models.CharField(blank=True, max_length=30, null=True)),
                ('viernes_fin_1', models.CharField(blank=True, max_length=30, null=True)),
                ('viernes_inicio_2', models.CharField(blank=True, max_length=30, null=True)),
                ('viernes_fin_2', models.CharField(blank=True, max_length=30, null=True)),
                ('viernes_inicio_3', models.CharField(blank=True, max_length=30, null=True)),
                ('viernes_fin_3', models.CharField(blank=True, max_length=30, null=True)),
                ('sabado_inicio_1', models.CharField(blank=True, max_length=30, null=True)),
                ('sabado_fin_1', models.CharField(blank=True, max_length=30, null=True)),
                ('sabado_inicio_2', models.CharField(blank=True, max_length=30, null=True)),
                ('sabado_fin_2', models.CharField(blank=True, max_length=30, null=True)),
                ('sabado_inicio_3', models.CharField(blank=True, max_length=30, null=True)),
                ('sabado_fin_3', models.CharField(blank=True, max_length=30, null=True)),
                ('domingo_inicio_1', models.CharField(blank=True, max_length=30, null=True)),
                ('domingo_fin_1', models.CharField(blank=True, max_length=30, null=True)),
                ('domingo_inicio_2', models.CharField(blank=True, max_length=30, null=True)),
                ('domingo_fin_2', models.CharField(blank=True, max_length=30, null=True)),
                ('domingo_inicio_3', models.CharField(blank=True, max_length=30, null=True)),
                ('domingo_fin_3', models.CharField(blank=True, max_length=30, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=30, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('nombres', models.CharField(max_length=300, verbose_name='Nombre(s)')),
                ('primer_apellido', models.CharField(max_length=100, verbose_name='Primer apellido')),
                ('segundo_apellido', models.CharField(max_length=100, verbose_name='Segundo apellido')),
                ('tipo_documento', models.CharField(choices=[('CC', 'Cedula de Ciudadania'), ('TI', 'Tarjeta de Identidad'), ('CE', 'Cedula Extranjera')], max_length=2, verbose_name='Tipo de documento')),
                ('numero_documento', models.CharField(max_length=20, unique=True, verbose_name='Numero de documento')),
                ('lugar_expedicion_documento', models.CharField(max_length=200, verbose_name='Lugar de expedicion')),
                ('telefono', models.CharField(max_length=10, verbose_name='Telefono de contacto')),
                ('genero', models.CharField(choices=[('Masculino', 'Masculino'), ('Femenino', 'Femenino')], max_length=20, verbose_name='Genero')),
                ('lugar_nacimiento', models.CharField(max_length=200, verbose_name='Lugar de nacimiento')),
                ('fecha_nacimiento', models.DateField()),
                ('rol', models.CharField(choices=[('Estudiante', 'Estudiante'), ('Director', 'Director'), ('Operario', 'Operario'), ('Administrador', 'Administrador')], max_length=30, verbose_name='Rol')),
                ('estado', models.CharField(choices=[('Activo', 'Activo'), ('Inactivo', 'Inactivo')], default='Activo', max_length=10, verbose_name='Estado')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Administrador',
            fields=[
                ('usuario_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            bases=('Usuarios.usuario',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Director',
            fields=[
                ('usuario_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('programa_academico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ProgramasAcademicos.ProgramaAcademico')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            bases=('Usuarios.usuario',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Estudiante',
            fields=[
                ('usuario_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('codigo', models.CharField(max_length=7, unique=True, verbose_name='Codigo de estudiante')),
                ('estado_d10', models.CharField(choices=[('No registrado', 'No registrado'), ('Registrado', 'Registrado')], default='No registrado', max_length=20, verbose_name='Estado d10')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            bases=('Usuarios.usuario',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Operario',
            fields=[
                ('usuario_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('cargo', models.CharField(max_length=100, verbose_name='Cargo')),
                ('dependencia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Dependencias.Dependencia')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            bases=('Usuarios.usuario',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.AddField(
            model_name='usuario',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions'),
        ),
        migrations.AddField(
            model_name='d10',
            name='datos_basicos',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Usuarios.DatosBasicosD10'),
        ),
        migrations.AddField(
            model_name='d10',
            name='datos_capacitacion',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Usuarios.DatosCapacitacionD10'),
        ),
        migrations.AddField(
            model_name='d10',
            name='datos_educacion',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Usuarios.DatosEducacionD10'),
        ),
        migrations.AddField(
            model_name='d10',
            name='datos_experiencia_laboral',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Usuarios.DatosExperienciaLaboralD10'),
        ),
        migrations.AddField(
            model_name='d10',
            name='datos_horario_disponible',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Usuarios.DatosHorarioDisponibleD10'),
        ),
        migrations.AddField(
            model_name='estudiante',
            name='d10',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Usuarios.D10'),
        ),
        migrations.AddField(
            model_name='estudiante',
            name='programa_academico',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ProgramasAcademicos.ProgramaAcademico'),
        ),
    ]
