# Generated by Django 2.0.7 on 2018-09-24 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='estudiante',
            name='estado_d10',
            field=models.CharField(default='Activo', max_length=20, verbose_name='Estado d10'),
        ),
    ]
