# Generated by Django 2.0.7 on 2018-09-26 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Usuarios', '0002_estudiante_estado_d10'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estudiante',
            name='estado_d10',
            field=models.CharField(choices=[('No registrado', 'No registrado'), ('Registrado', 'Registrado')], default='No registrado', max_length=20, verbose_name='Estado d10'),
        ),
    ]
